apiVersion: v1
kind: Service
metadata:
  name: {{ include "spma.fullname" . }}-api
  labels:
    {{- include "spma.labels" . | nindent 4 }}
    component: api
spec:
  type: {{ .Values.api.service.type }}
  ports:
  - port: {{ .Values.api.service.port }}
    targetPort: {{ .Values.api.service.port }}
    protocol: TCP
    name: http
  selector:
    {{- include "spma.selectorLabels" . | nindent 4 }}
    component: api
