apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "spma.fullname" . }}-config
  labels:
    {{- include "spma.labels" . | nindent 4 }}
data:
  spma.yaml: |
    {{ .Files.Get "config/spma.yaml" | nindent 4 }}
