apiVersion: v1
kind: Secret
metadata:
  name: {{ include "spma.fullname" . }}-secrets
  labels:
    {{- include "spma.labels" . | nindent 4 }}
type: Opaque
stringData:
  anthropic-api-key: {{ .Values.external.llmApi.anthropicApiKey | quote }}
  postgres-readonly-url: {{ .Values.external.postgres.readonlyReplicaUrl | quote }}
  pgvector-url: {{ .Values.external.postgres.readonlyReplicaUrl | quote }}
  redis-url: {{ .Values.external.redis.url | quote }}
