# config/es_mapping.yaml
index_name: spma_docs
settings:
  number_of_shards: 1
  number_of_replicas: 0
  refresh_interval: "1s"
  analysis:
    analyzer:
      ik_smart_analyzer:
        type: custom
        tokenizer: ik_smart
mappings:
  properties:
    chunk_id:
      type: keyword
    source_id:
      type: keyword
    source_type:
      type: keyword
    req_ids:
      type: keyword
    content:
      type: text
      analyzer: ik_smart_analyzer
      search_analyzer: ik_smart_analyzer
    doc_type:
      type: keyword
    version:
      type: keyword
    updated_at:
      type: date
    chunk_index:
      type: integer
    page_title:
      type: text
      analyzer: ik_smart_analyzer
      fields:
        keyword:
          type: keyword
